name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change the version if needed

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build   # Use this if you need to build your project
          npm run export  # For static export (Next.js or other frameworks)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # The folder where your static files are built
